/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/observation` | `/home/observation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/showcase-final` | `/home/showcase-final`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/showcase` | `/home/showcase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload` | `/home/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload2` | `/home/upload2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload3` | `/home/upload3`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/observation` | `/home/observation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/showcase-final` | `/home/showcase-final`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/showcase` | `/home/showcase`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/upload` | `/home/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/upload2` | `/home/upload2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home/upload3` | `/home/upload3`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/observation${`?${string}` | `#${string}` | ''}` | `/home/observation${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/showcase-final${`?${string}` | `#${string}` | ''}` | `/home/showcase-final${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/showcase${`?${string}` | `#${string}` | ''}` | `/home/showcase${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/upload${`?${string}` | `#${string}` | ''}` | `/home/upload${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/upload2${`?${string}` | `#${string}` | ''}` | `/home/upload2${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home/upload3${`?${string}` | `#${string}` | ''}` | `/home/upload3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/observation` | `/home/observation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/showcase-final` | `/home/showcase-final`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/showcase` | `/home/showcase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload` | `/home/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload2` | `/home/upload2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home/upload3` | `/home/upload3`; params?: Router.UnknownInputParams; };
    }
  }
}
